trigger:
- week1

pool: My Computer Agent

steps:
- task: AzureCLI@2
  displayName: 'Running Pipeline Script'
  inputs:
    azureSubscription: 'My Azure Students Subscription'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'pipeline-script.sh'
