pipeline {
    agent any

    parameters {
        choice(name: 'CHOICES', choices: ['apply', 'destroy'], description: 'Depends on input pipeline will trigger')
        string(name: 'S3_Bucket', defaultValue: 'www.cloudenthusiastic.online', description: 'Please enter your website name. e.g. www.cloudenthusiastic.online')
    }

    environment {
        AWS_REGION = 'us-east-1'  // Change to your desired AWS region
        S3_BUCKET = 'www.cloudenthusiastic.online'  // Your S3 bucket name
    }

    // stages {
    //     stage('Code Checkout') {
    //         steps {
    //             echo 'No need as we are using pipeline script for checkout'
    //             git branch: 'main', url: 'https://github.com/SapkalKunal96/devopsK.git'
    //         }
    //     }

        stage('Terraform Init') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'jenkins-aws-key-id']]) {
                    script {
                        sh """
                            terraform --version
                            cd /var/lib/jenkins/workspace/01.S3Bucket/01.S3bucketStaticWebHosting/terraform
                            terraform init
                        """
                    }
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { return params.CHOICES == 'apply' }
            }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'jenkins-aws-key-id']]) {
                    script {
                        sh """
                            cd terraform
                            terraform apply --auto-approve
                        """
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { return params.CHOICES == 'destroy' }
            }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'jenkins-aws-key-id']]) {
                    script {
                        sh """
                            cd terraform
                            terraform destroy --auto-approve
                        """
                    }
                }
            }
        }

        stage('Pushing code to S3') {
            steps {
                // Set AWS credentials using Jenkins' AWS Credentials plugin
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'jenkins-aws-key-id']]) {
                    script {
                        try {
                            sh """
                                aws s3 ls
                                cd ../website
                                aws s3 sync . s3://${params.S3_Bucket}/ 
                            """
                        } catch (Exception e) {
                            error "AWS S3 sync failed: ${e.getMessage()}"
                        }
                    }
                }
            }
        }

        stage('Test Website') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'jenkins-aws-key-id']]) {
                    sh 'curl http://www.cloudenthusiastic.online.s3-website-us-east-1.amazonaws.com'
                    // Add your deployment steps here
                }
            }
        }
    }

